name: NaniApp
description: "Una app para recordar inyecciones cada 30 dias."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.0

flutter:
  uses-material-design: true